### ISSUE TITLE
Mysql Bug

### ISSUE THREAD

**Issue by hirowatch** [hlmod/Shop-Core#108]
L 10/13/2021 - 13:46:49: [SHOPCore/SHOP_Core.smx] DB_ErrorCheck: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IGNORE TABLE `shop_players` ADD `lastconnect` int(10) NOT NULL DEFAULT '0'' at line 1
L 10/13/2021 - 13:46:49: [SHOPCore/SHOP_Core.smx] DB_UgradeState_1: Table 'name_base.shop_items' doesn't exist

**Server (please complete the following information):**
 - OS: [Linux]
 - Sourcemod version [1.10.0.6490]
 - Version ["[Shop] Core" (3.0E2)]
 - Game CSSv34

**Comment by CrazyHackGUT** [comment]
https://dev.mysql.com/worklog/task/?id=7395
Looks like it removed.

**Comment by hirowatch** [comment]
Hi! Edit mysql.

![изображение](https://user-images.githubusercontent.com/40771558/163690633-144b1520-521e-4473-8d82-d44b3f7d7ebf.png)

lastconnect int(10)

The error is gone
