### ISSUE TITLE
ChatGPT module generation support

### ISSUE THREAD

**Issue by inklesspen1rus** [hlmod/Shop-Core#155]
**Is your feature request related to a problem? Please describe.**
ChatGPT can generate source code using almost any language. It can generate sourcepawn plugins also. But when it generates plugin using Shop Core, It uses non-exists native Shop_AddPlayerCredits so plugin does not compile.

**Describe the solution you'd like**
Let ChatGPT generate valid source code by adding non-exists function.
Add stock-function to call `Shop_GiveClientCredits` under the hood:
```
stock int Shop_AddPlayerCredits(int client, int amount, int by_who = CREDITS_BY_NATIVE) {
    return Shop_GiveClientCredits(client, amount, by_who);
}
```

**Describe alternatives you've considered**
Add new `Shop_AddPlayerCredits` native, similar to `Shop_GiveClientCredits`:
```
native int Shop_AddPlayerCredits(int client, int amount, int by_who = CREDITS_BY_NATIVE);
```

**Additional context**
![изображение](https://user-images.githubusercontent.com/22255205/211017235-f52efb31-3bb9-476e-a2c2-6d526ca04e8a.png)

**Comment by TiBarification** [comment]
ChatGPT have a lot of issues and false-positives. The code its generate is unapplicable for game servers in most cases. We are not ready to use neural network for such kind of things.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/6222472/211031982-6ea7cccd-2a7e-447c-bedc-2cbb78dd17f8.png)
