### ISSUE TITLE
"Raw" manual SQL queries

### ISSUE THREAD

**Issue by CrazyHackGUT** [hlmod/Shop-Core#31]
Add feature for manual running "raw SQL queries", like: 
```sql
UPDATE `shop_players` SET `money` = 0 
```

**Comment by TiBarification** [comment]
For security reasons i'm thinking that query must be opened from file, and console command to open that file with query / queries.

**Comment by TiBarification** [comment]
@CrazyHackGUT do we need to keep this feature? I think there no reason to integrate such kind things. Game server admins might resolve these issues by themself, why we should integrate database management inside core?

**Comment by CrazyHackGUT** [comment]
I guess no. This can be done via custom plugin.
